version: "3.9"
services:
  db:
    build: ./db
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: e-commerce
      MYSQL_ROOT_PASSWORD: P@ssword1234
    ports:
      - "33061:3306"
    volumes:
      - mini_e_commerce_mysql_data:/var/lib/mysql # เปลี่ยน path เป็น volume ที่เราสร้างไปด้านล่างใน docker-compose
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db # ระบุ host ที่จะให้ phpmyadmin ไปจัดการ ซึ่งสามารถใส่เป็นชื่อ container name (db) ได้เลย
      PMA_PORT: 3306 # ระบุ port ของ Database
      PMA_USER: root # ระบุ user ของ Database
      PMA_PASSWORD: P@ssword1234 # ระบุ password ของ Database
    depends_on:
      - db
  backend:
    build: .
    container_name: backend_container
    environment:
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssword1234
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
volumes:
  mini_e_commerce_mysql_data: # กำหนดชื่อ volume ที่ต้องการจะสร้าง
    driver: local
